### ISSUE TITLE
dataset clarity

### ISSUE THREAD

**Issue by purvanshi** [DeepLearning4BioSeqText/Paper16-DeepChrome#3]
Hello,
Could you please provide a detailed readme of how the data was generated. I referred to #2 but its still confusing. Proper steps would be beneficial for all. 
Could you please explain the toy data. I understand from the paper that 5  five selected histone modifications from REMC were used as x and the output of gene expression (+1/-1) as y. I couldn't find the column labelling anywhere(which column denotes what and which column is the output).

Thanking you in advance.
Purvanshi

**Comment by rs3zz** [comment]
Hello Purvanshi,

I apologize for the delay. I somehow missed seeing this comment. The column labels are as follows for the toy dataset - GeneID, Bin Number, HM1, HM2, HM3, HM4, HM5, Label. Here HM= Histone Modification and HM1=H3K27me3, HM2=H3K36me3, HM3=H3K4me1, HM4=H3K4me3, and HM5=H3K9me3. 

As far as data generation steps are concerned, I will try and write a more detailed readme. Meanwhile, is there anything specific you are confused about?  

Regards
Ritambhara
