### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by aidanmacnamara** [DeepLearning4BioSeqText/Paper16-DeepChrome#4]
Hello,

Many thanks for the package. I'm getting an error with the attached input. Specifically, the AUC score is returning 'nan' (in train.log). I can't see anything that I'm missing so any help would be appreciated!

Many thanks, Aidan
[train.txt](https://github.com/QData/DeepChrome/files/1824500/train.txt)

**Comment by jacklanchantin** [comment]
Hi @aidanmacnamara  we are working on updating this code to pytorch, which should fix this issue.
